# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h_dist_cpp <- function(x, m, two_level, quali) {
    .Call(`_HiGarrote_h_dist_cpp`, x, m, two_level, quali)
}

h_j_cpp <- function(p, uni_level, m_list, two_level_id, quali_id) {
    .Call(`_HiGarrote_h_j_cpp`, p, uni_level, m_list, two_level_id, quali_id)
}

Psi_mat_cpp <- function(h_list_mat, rho) {
    .Call(`_HiGarrote_Psi_mat_cpp`, h_list_mat, rho)
}

rho_lambda_optim <- function(ini_point, h_list_mat, n, replicate, y, lambda_lb, lambda_ub) {
    .Call(`_HiGarrote_rho_lambda_optim`, ini_point, h_list_mat, n, replicate, y, lambda_lb, lambda_ub)
}

initialize_BETA_instance <- function(h_j_list, p, rho_list, mi) {
    invisible(.Call(`_HiGarrote_initialize_BETA_instance`, h_j_list, p, rho_list, mi))
}

r_j_cpp_R <- function(U_j_list, me_num) {
    .Call(`_HiGarrote_r_j_cpp_R`, U_j_list, me_num)
}

beta_ele_cpp_R <- function(U, R, lambda, replicate, n, y) {
    .Call(`_HiGarrote_beta_ele_cpp_R`, U, R, lambda, replicate, n, y)
}

beta_nng_cpp_R <- function(beta_ele, replicate, n, y, Amat, s2) {
    .Call(`_HiGarrote_beta_nng_cpp_R`, beta_ele, replicate, n, y, Amat, s2)
}

